
// Common grocery items in Portuguese
export const commonGroceryItems = [
  { name: "Arroz", icon: "Wheat" },
  { name: "Feijão", icon: "Bean" },
  { name: "Açúcar", icon: "Cookie" },
  { name: "Café", icon: "Coffee" },
  { name: "Leite", icon: "Milk" },
  { name: "Pão", icon: "Bread" },
  { name: "Manteiga", icon: "Dessert" },
  { name: "Queijo", icon: "Cheese" },
  { name: "Ovos", icon: "Egg" },
  { name: "Carne", icon: "Beef" },
  { name: "Frango", icon: "ChefHat" },
  { name: "Peixe", icon: "Fish" },
  { name: "Maçã", icon: "Apple" },
  { name: "Banana", icon: "Banana" },
  { name: "Laranja", icon: "Orange" },
  { name: "Tomate", icon: "Beef" },
  { name: "Batata", icon: "Potato" },
  { name: "Cenoura", icon: "Carrot" },
  { name: "Alface", icon: "Leaf" },
  { name: "Água", icon: "Droplets" },
  { name: "Refrigerante", icon: "Beer" },
  { name: "Suco", icon: "Coffee" },
  { name: "Cerveja", icon: "Beer" },
  { name: "Papel Higiênico", icon: "ScrollText" },
  { name: "Sabonete", icon: "Soap" },
  { name: "Shampoo", icon: "Droplets" },
  { name: "Pasta de Dente", icon: "Toothbrush" },
  { name: "Detergente", icon: "Droplets" },
  { name: "Sabão em Pó", icon: "Snowflake" },
  { name: "Amaciante", icon: "Heart" }
];
